### ISSUE TITLE
Reproducing Cityscapes results

### ISSUE THREAD

**Issue by DdeGeus** [yanwei-li/PanopticFCN#21]
Thanks for providing the code for Panoptic FCN, I think it’s a very interesting method!

As this repo only provides the training/evaluation code for COCO, I adapted the code to work for Cityscapes. [In this fork](https://github.com/DdeGeus/PanopticFCN_cityscapes), I added a data pipeline for Cityscapes, changed the configs as mentioned in the CVPR paper, and made some other minor necessary changes in the code.

However, when I run with the mentioned config, I cannot reproduce the results on Cityscapes as reported in the paper. Especially for the things classes, the difference is quite large. Specifically, this is the difference in performance:

<table><tbody>
<th>Method</th>
<th>Backbone</th>
<th>PQ</th>
<th>PQ_th</th>
<th>PQ_st</th>
<tr>
<td align="left">Panoptic FCN (reported in paper)</td>
<td align="center">R-50</td>
<td align="center">59.6</td>
<td align="center">52.1</td>
<td align="center">65.1</td>
</tr>
<td align="left">Panoptic FCN (reproduced in our fork)</td>
<td align="center">R-50</td>
<td align="center">58.1</td>
<td align="center">49.3</td>
<td align="center">64.6</td>
</tr>
</tbody></table>

To be more specific, the following changes are made to the config yaml:

```yaml
MODEL:
  LOSS_WEIGHT:
    SEGMENT: 4.0
  POSITION_HEAD:
    THING:
      NUM_CLASSES: 8
    STUFF:
      NUM_CLASSES: 12
      WITH_THING: True
  SEM_SEG_HEAD:
    NUM_CLASSES: 12
  KERNEL_HEAD:
    INSTANCE_SCALES: ((1, 128), (64, 256), (128, 512), (256, 1024), (512, 2048),)
  TENSOR_DIM: 150  # Adapted because max inst. per img > 100

SOLVER:
  BASE_LR: 0.02
  IMS_PER_BATCH: 32
  MAX_ITER: 65000

INPUT:
  MIN_SIZE_TRAIN: (512, 2048)
  MIN_SIZE_TRAIN_SAMPLING: "range"
  MIN_SIZE_TEST: 1024
  MAX_SIZE_TRAIN: 4096
  MAX_SIZE_TEST: 2048
  CROP:
    ENABLED: True
    TYPE: "absolute"
    SIZE: (512, 1024)
```

Is there something that I am missing? Are there further changes that need to be made to the code/config to be able to reproduce the Cityscapes result?

In issue #20<insert URL> I read that you mention that the ``SEM_SEG_HEAD`` should be trained on all 19 classes instead of just the 12 classes (11 stuff + 1 for all things). Is this how you train it to produce the results you report in the paper? Did you notice a difference in performance for both versions? 

Looking forward to your response. Thanks!

**Comment by yanwei-li** [comment]
Hi, thanks for your interest in our work! The differences with your config are given below. Most of them are adjusted according to the data properties in the cityscapes dataset. And we use 19 classes for stuff training, which would bring some performance gain.
```
MODEL:
  POSITION_HEAD:
    THING:
      NUM_CLASSES: 19
      THRES: 0.01
      TOP_NUM: 200
    STUFF:
      THRES: 0.1
  INFERENCE:
    INST_THRES=0.5
    SIMILAR_THRES=0.97
    COMBINE:
       STUFF_AREA_LIMIT=2048
  
INPUT:  
  MIN_SIZE_TRAIN: (512, 768, 1024, 1152, 1216, 1344, 1408, 1536, 1664, 1728, 1856, 1920, 2048)
  MIN_SIZE_TRAIN_SAMPLING: "choice"
  MIN_SIZE_TEST: 1024 
  MAX_SIZE_TRAIN: 4096  
  MAX_SIZE_TEST: 2048
  CROP:
    ENABLED: True
    TYPE: "with_instance" # implemented by ourself to ensure some instances in the crops
    SIZE: (512, 1024)
```
Maybe you can try this for the result. Hope this could help you.
